UPDATE openhack.hackathon SET description = 'hackathon event', discount = null, end_date = '2019-06-30', fee = 20, is_closed = true, is_finalized = true, max_size = 5, min_size = 3, name = 'FakeHackathon', start_date = '2019-04-30' WHERE id = 1;
UPDATE openhack.hackathon SET description = 'big hackathon event in SJ', discount = null, end_date = '2019-08-30', fee = 10, is_closed = true, is_finalized = true, max_size = 5, min_size = 2, name = 'Hackathon AA 2019', start_date = '2019-05-08' WHERE id = 2;
UPDATE openhack.hackathon SET description = 'One of the biggest hackathon event holding in Summer 2019. All programmars are welcome to participate in this event. The first prize for the event will be a reward of $1000 dollars. This hackathon is mainly about hackers design IoT products.', discount = null, end_date = '2019-09-20', fee = 10, is_closed = true, is_finalized = false, max_size = 5, min_size = 1, name = 'SJ Hackathon event 2019', start_date = '2019-05-08' WHERE id = 3;
UPDATE openhack.hackathon SET description = 'This hackathon is one of the biggest hackathon events in the bay area. It is held every year with an average of 4000 hackers participating. The final reward is $10,000! Participate soon for this event!', discount = 80, end_date = '2019-09-01', fee = 30, is_closed = false, is_finalized = false, max_size = 4, min_size = 1, name = 'Best Hackathon in Bay area', start_date = '2019-05-08' WHERE id = 4;
UPDATE openhack.hackathon SET description = 'a new hackerthon', discount = 3, end_date = '2019-05-05', fee = 13, is_closed = false, is_finalized = false, max_size = 5, min_size = 2, name = 'new hack', start_date = '2019-04-30' WHERE id = 5;
UPDATE openhack.hackathon SET description = 'Best Hackathon in US!', discount = 70, end_date = '2019-12-10', fee = 20, is_closed = false, is_finalized = false, max_size = 10, min_size = 2, name = 'Test Hackathon ', start_date = '2019-05-10' WHERE id = 6;
UPDATE openhack.hackathon SET description = 'test', discount = 10, end_date = '2019-06-13', fee = 100, is_closed = false, is_finalized = false, max_size = 5, min_size = 1, name = 'HappyHack', start_date = '2019-05-08' WHERE id = 7;
UPDATE openhack.hackathon_judges SET hackathon_id = 1, jdg_hacker_id = 6;
UPDATE openhack.hackathon_judges SET hackathon_id = 1, jdg_hacker_id = 9;
UPDATE openhack.hackathon_judges SET hackathon_id = 2, jdg_hacker_id = 6;
UPDATE openhack.hackathon_judges SET hackathon_id = 3, jdg_hacker_id = 21;
UPDATE openhack.hackathon_judges SET hackathon_id = 4, jdg_hacker_id = 16;
UPDATE openhack.hackathon_judges SET hackathon_id = 6, jdg_hacker_id = 14;
UPDATE openhack.hackathon_judges SET hackathon_id = 7, jdg_hacker_id = 25;
UPDATE openhack.hackathon_sponsors SET hackathon_id = 2, spr_org_id = 4;
UPDATE openhack.hackathon_sponsors SET hackathon_id = 3, spr_org_id = 7;
UPDATE openhack.hackathon_sponsors SET hackathon_id = 4, spr_org_id = 8;
UPDATE openhack.hackathon_sponsors SET hackathon_id = 5, spr_org_id = 7;
UPDATE openhack.hackathon_sponsors SET hackathon_id = 6, spr_org_id = 7;
UPDATE openhack.hackathon_sponsors SET hackathon_id = 7, spr_org_id = 10;
UPDATE openhack.hibernate_sequence SET next_val = 1;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 9, team_id = null WHERE id = 1;
UPDATE openhack.member SET if_paid = false, role = 'Engineer', hackeruser_id = 6, team_id = null WHERE id = 2;
UPDATE openhack.member SET if_paid = false, role = 'Data Engineer', hackeruser_id = 9, team_id = null WHERE id = 3;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 12, team_id = 2 WHERE id = 4;
UPDATE openhack.member SET if_paid = false, role = 'Engineer', hackeruser_id = 13, team_id = 2 WHERE id = 5;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 13, team_id = 3 WHERE id = 6;
UPDATE openhack.member SET if_paid = false, role = 'Senior Engineer', hackeruser_id = 14, team_id = 3 WHERE id = 7;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 13, team_id = 4 WHERE id = 8;
UPDATE openhack.member SET if_paid = false, role = 'frontend', hackeruser_id = 19, team_id = 4 WHERE id = 9;
UPDATE openhack.member SET if_paid = false, role = 'backend', hackeruser_id = 18, team_id = 4 WHERE id = 10;
UPDATE openhack.member SET if_paid = false, role = 'manager', hackeruser_id = 17, team_id = 4 WHERE id = 11;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 13, team_id = 5 WHERE id = 12;
UPDATE openhack.member SET if_paid = false, role = 'manager', hackeruser_id = null, team_id = 5 WHERE id = 13;
UPDATE openhack.member SET if_paid = false, role = 'backend', hackeruser_id = null, team_id = 5 WHERE id = 14;
UPDATE openhack.member SET if_paid = false, role = 'frontend', hackeruser_id = null, team_id = 5 WHERE id = 15;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 13, team_id = 6 WHERE id = 16;
UPDATE openhack.member SET if_paid = false, role = 'manager', hackeruser_id = null, team_id = 6 WHERE id = 17;
UPDATE openhack.member SET if_paid = false, role = 'backend', hackeruser_id = null, team_id = 6 WHERE id = 18;
UPDATE openhack.member SET if_paid = false, role = 'frontend', hackeruser_id = null, team_id = 6 WHERE id = 19;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 13, team_id = 7 WHERE id = 20;
UPDATE openhack.member SET if_paid = false, role = 'manager', hackeruser_id = null, team_id = 7 WHERE id = 21;
UPDATE openhack.member SET if_paid = false, role = 'backend', hackeruser_id = null, team_id = 7 WHERE id = 22;
UPDATE openhack.member SET if_paid = false, role = 'frontend', hackeruser_id = null, team_id = 7 WHERE id = 23;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 13, team_id = 8 WHERE id = 24;
UPDATE openhack.member SET if_paid = false, role = 'manager', hackeruser_id = null, team_id = 8 WHERE id = 25;
UPDATE openhack.member SET if_paid = false, role = 'backend', hackeruser_id = null, team_id = 8 WHERE id = 26;
UPDATE openhack.member SET if_paid = false, role = 'frontend', hackeruser_id = null, team_id = 8 WHERE id = 27;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 13, team_id = 9 WHERE id = 28;
UPDATE openhack.member SET if_paid = false, role = 'manager', hackeruser_id = null, team_id = 9 WHERE id = 29;
UPDATE openhack.member SET if_paid = false, role = 'manager', hackeruser_id = null, team_id = 9 WHERE id = 30;
UPDATE openhack.member SET if_paid = false, role = 'manager', hackeruser_id = null, team_id = 9 WHERE id = 31;
UPDATE openhack.member SET if_paid = true, role = 'Team Lead', hackeruser_id = 13, team_id = 10 WHERE id = 32;
UPDATE openhack.member SET if_paid = true, role = 'manager', hackeruser_id = null, team_id = 10 WHERE id = 33;
UPDATE openhack.member SET if_paid = true, role = 'manager', hackeruser_id = 21, team_id = 10 WHERE id = 34;
UPDATE openhack.member SET if_paid = true, role = 'manager', hackeruser_id = 19, team_id = 10 WHERE id = 35;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 21, team_id = 11 WHERE id = 36;
UPDATE openhack.member SET if_paid = false, role = 'Senior Engineer', hackeruser_id = 19, team_id = 11 WHERE id = 37;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 13, team_id = 12 WHERE id = 38;
UPDATE openhack.member SET if_paid = false, role = 'maneger', hackeruser_id = null, team_id = 12 WHERE id = 39;
UPDATE openhack.member SET if_paid = false, role = 'frontend', hackeruser_id = null, team_id = 12 WHERE id = 40;
UPDATE openhack.member SET if_paid = false, role = 'backend', hackeruser_id = null, team_id = 12 WHERE id = 41;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 13, team_id = 13 WHERE id = 42;
UPDATE openhack.member SET if_paid = false, role = 'maneger', hackeruser_id = null, team_id = 13 WHERE id = 43;
UPDATE openhack.member SET if_paid = false, role = 'frontend', hackeruser_id = null, team_id = 13 WHERE id = 44;
UPDATE openhack.member SET if_paid = false, role = 'backend', hackeruser_id = null, team_id = 13 WHERE id = 45;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 16, team_id = 14 WHERE id = 46;
UPDATE openhack.member SET if_paid = false, role = 'manager', hackeruser_id = 17, team_id = 14 WHERE id = 47;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 16, team_id = 15 WHERE id = 48;
UPDATE openhack.member SET if_paid = false, role = 'engineer', hackeruser_id = 14, team_id = 15 WHERE id = 49;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 16, team_id = 16 WHERE id = 50;
UPDATE openhack.member SET if_paid = false, role = 'engineer', hackeruser_id = 14, team_id = 16 WHERE id = 51;
UPDATE openhack.member SET if_paid = false, role = 'data', hackeruser_id = 17, team_id = 16 WHERE id = 52;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 13, team_id = 17 WHERE id = 53;
UPDATE openhack.member SET if_paid = false, role = 'manager', hackeruser_id = null, team_id = 17 WHERE id = 54;
UPDATE openhack.member SET if_paid = false, role = 'ds', hackeruser_id = null, team_id = 17 WHERE id = 55;
UPDATE openhack.member SET if_paid = false, role = 'sad', hackeruser_id = null, team_id = 17 WHERE id = 56;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 16, team_id = 18 WHERE id = 57;
UPDATE openhack.member SET if_paid = false, role = 'manager', hackeruser_id = 21, team_id = 18 WHERE id = 58;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 13, team_id = 19 WHERE id = 59;
UPDATE openhack.member SET if_paid = false, role = 'manager', hackeruser_id = null, team_id = 19 WHERE id = 60;
UPDATE openhack.member SET if_paid = false, role = 'frontend', hackeruser_id = 21, team_id = 19 WHERE id = 61;
UPDATE openhack.member SET if_paid = false, role = 'backend', hackeruser_id = 20, team_id = 19 WHERE id = 62;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 13, team_id = 20 WHERE id = 63;
UPDATE openhack.member SET if_paid = false, role = 'manager', hackeruser_id = null, team_id = 20 WHERE id = 64;
UPDATE openhack.member SET if_paid = false, role = 'frontend', hackeruser_id = 21, team_id = 20 WHERE id = 65;
UPDATE openhack.member SET if_paid = false, role = 'backend', hackeruser_id = 20, team_id = 20 WHERE id = 66;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 13, team_id = 21 WHERE id = 67;
UPDATE openhack.member SET if_paid = false, role = 'manager', hackeruser_id = 19, team_id = 21 WHERE id = 68;
UPDATE openhack.member SET if_paid = false, role = 'frontend', hackeruser_id = 21, team_id = 21 WHERE id = 69;
UPDATE openhack.member SET if_paid = false, role = 'backend', hackeruser_id = 20, team_id = 21 WHERE id = 70;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 16, team_id = 22 WHERE id = 71;
UPDATE openhack.member SET if_paid = false, role = 'engineer', hackeruser_id = null, team_id = 22 WHERE id = 72;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 10, team_id = 23 WHERE id = 73;
UPDATE openhack.member SET if_paid = false, role = 'manager', hackeruser_id = 17, team_id = 23 WHERE id = 74;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 10, team_id = 24 WHERE id = 75;
UPDATE openhack.member SET if_paid = false, role = 'backend', hackeruser_id = 17, team_id = 24 WHERE id = 76;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 16, team_id = 25 WHERE id = 77;
UPDATE openhack.member SET if_paid = false, role = 'manager', hackeruser_id = 17, team_id = 25 WHERE id = 78;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 16, team_id = 26 WHERE id = 79;
UPDATE openhack.member SET if_paid = false, role = 'serfewf', hackeruser_id = null, team_id = 26 WHERE id = 80;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 16, team_id = 27 WHERE id = 81;
UPDATE openhack.member SET if_paid = false, role = 'sdfge', hackeruser_id = 17, team_id = 27 WHERE id = 82;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 10, team_id = 28 WHERE id = 83;
UPDATE openhack.member SET if_paid = false, role = 'manager', hackeruser_id = 17, team_id = 28 WHERE id = 84;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 10, team_id = 29 WHERE id = 85;
UPDATE openhack.member SET if_paid = false, role = 'dasfd', hackeruser_id = 17, team_id = 29 WHERE id = 86;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 10, team_id = 30 WHERE id = 87;
UPDATE openhack.member SET if_paid = false, role = 'manager', hackeruser_id = 21, team_id = 30 WHERE id = 88;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 10, team_id = 31 WHERE id = 89;
UPDATE openhack.member SET if_paid = false, role = 'front', hackeruser_id = 17, team_id = 31 WHERE id = 90;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 16, team_id = 32 WHERE id = 91;
UPDATE openhack.member SET if_paid = false, role = 'sdf', hackeruser_id = 17, team_id = 32 WHERE id = 92;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 16, team_id = 33 WHERE id = 93;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 16, team_id = 34 WHERE id = 94;
UPDATE openhack.member SET if_paid = false, role = 'Team Lead', hackeruser_id = 27, team_id = 35 WHERE id = 95;
UPDATE openhack.organization SET city = null, state = null, street = null, zip = null, description = 'AA', name = 'test', user_id = 9 WHERE id = 3;
UPDATE openhack.organization SET city = 'SJ', state = null, street = null, zip = '95036', description = 'biggest org in Bay area', name = 'ABC', user_id = 9 WHERE id = 4;
UPDATE openhack.organization SET city = 'CUPERTINO', state = 'California', street = '10113 parkwood drive apt8', zip = '95014', description = 'good engineer', name = 'study', user_id = 17 WHERE id = 7;
UPDATE openhack.organization SET city = 'CUPERTINO', state = 'California', street = '10113 parkwood drive apt8', zip = '95014', description = null, name = 'janney', user_id = 17 WHERE id = 8;
UPDATE openhack.organization SET city = 'sdf', state = 'sdf', street = 'dfe', zip = 'ssf', description = 'sss', name = 'SuperOrg', user_id = 16 WHERE id = 9;
UPDATE openhack.organization SET city = 'San Jose', state = 'CA', street = '123 Fake St', zip = '95051', description = 'organization for demo purpose', name = 'BestCloud', user_id = 25 WHERE id = 10;
UPDATE openhack.team SET grade = 80, if_all_paid = false, team_name = 'Super', url = 'XXX', hackthon_id = 1, teamlead_memberid = 1, hackathon_id = null, hackthon_ids = null WHERE id = 1;
UPDATE openhack.team SET grade = null, if_all_paid = false, team_name = 'Rocket', url = null, hackthon_id = 2, teamlead_memberid = 4, hackathon_id = null, hackthon_ids = null WHERE id = 2;
UPDATE openhack.team SET grade = null, if_all_paid = false, team_name = 'Space', url = null, hackthon_id = 2, teamlead_memberid = 6, hackathon_id = null, hackthon_ids = null WHERE id = 3;
UPDATE openhack.team SET grade = null, if_all_paid = null, team_name = null, url = null, hackthon_id = 2, teamlead_memberid = 8, hackathon_id = null, hackthon_ids = null WHERE id = 4;
UPDATE openhack.team SET grade = null, if_all_paid = null, team_name = null, url = null, hackthon_id = 2, teamlead_memberid = 12, hackathon_id = null, hackthon_ids = null WHERE id = 5;
UPDATE openhack.team SET grade = null, if_all_paid = null, team_name = null, url = null, hackthon_id = 2, teamlead_memberid = 16, hackathon_id = null, hackthon_ids = null WHERE id = 6;
UPDATE openhack.team SET grade = null, if_all_paid = null, team_name = null, url = null, hackthon_id = 2, teamlead_memberid = 20, hackathon_id = null, hackthon_ids = null WHERE id = 7;
UPDATE openhack.team SET grade = null, if_all_paid = null, team_name = null, url = null, hackthon_id = 2, teamlead_memberid = 24, hackathon_id = null, hackthon_ids = null WHERE id = 8;
UPDATE openhack.team SET grade = null, if_all_paid = null, team_name = null, url = null, hackthon_id = 2, teamlead_memberid = 28, hackathon_id = null, hackthon_ids = null WHERE id = 9;
UPDATE openhack.team SET grade = null, if_all_paid = null, team_name = null, url = null, hackthon_id = 2, teamlead_memberid = 32, hackathon_id = null, hackthon_ids = null WHERE id = 10;
UPDATE openhack.team SET grade = null, if_all_paid = false, team_name = 'Sky', url = null, hackthon_id = 3, teamlead_memberid = 36, hackathon_id = null, hackthon_ids = null WHERE id = 11;
UPDATE openhack.team SET grade = null, if_all_paid = false, team_name = null, url = null, hackthon_id = 2, teamlead_memberid = 38, hackathon_id = null, hackthon_ids = null WHERE id = 12;
UPDATE openhack.team SET grade = null, if_all_paid = false, team_name = null, url = null, hackthon_id = 2, teamlead_memberid = 42, hackathon_id = null, hackthon_ids = null WHERE id = 13;
UPDATE openhack.team SET grade = null, if_all_paid = false, team_name = null, url = null, hackthon_id = 3, teamlead_memberid = 46, hackathon_id = null, hackthon_ids = null WHERE id = 14;
UPDATE openhack.team SET grade = null, if_all_paid = false, team_name = 'null', url = null, hackthon_id = 3, teamlead_memberid = 48, hackathon_id = null, hackthon_ids = null WHERE id = 15;
UPDATE openhack.team SET grade = null, if_all_paid = true, team_name = 'null', url = null, hackthon_id = 3, teamlead_memberid = 50, hackathon_id = null, hackthon_ids = null WHERE id = 16;
UPDATE openhack.team SET grade = null, if_all_paid = false, team_name = 'hackers', url = null, hackthon_id = 2, teamlead_memberid = 53, hackathon_id = null, hackthon_ids = null WHERE id = 17;
UPDATE openhack.team SET grade = null, if_all_paid = false, team_name = 'RRR', url = null, hackthon_id = 3, teamlead_memberid = 57, hackathon_id = null, hackthon_ids = null WHERE id = 18;
UPDATE openhack.team SET grade = null, if_all_paid = false, team_name = 'hakersss', url = null, hackthon_id = 2, teamlead_memberid = 59, hackathon_id = null, hackthon_ids = null WHERE id = 19;
UPDATE openhack.team SET grade = null, if_all_paid = false, team_name = 'hakersss', url = null, hackthon_id = 2, teamlead_memberid = 63, hackathon_id = null, hackthon_ids = null WHERE id = 20;
UPDATE openhack.team SET grade = null, if_all_paid = false, team_name = 'hakersss', url = null, hackthon_id = 2, teamlead_memberid = 67, hackathon_id = null, hackthon_ids = null WHERE id = 21;
UPDATE openhack.team SET grade = null, if_all_paid = false, team_name = 'Warrior', url = null, hackthon_id = 6, teamlead_memberid = 71, hackathon_id = null, hackthon_ids = null WHERE id = 22;
UPDATE openhack.team SET grade = null, if_all_paid = false, team_name = 'superteam', url = null, hackthon_id = 6, teamlead_memberid = 73, hackathon_id = null, hackthon_ids = null WHERE id = 23;
UPDATE openhack.team SET grade = null, if_all_paid = false, team_name = 'hhh', url = null, hackthon_id = 6, teamlead_memberid = 75, hackathon_id = null, hackthon_ids = null WHERE id = 24;
UPDATE openhack.team SET grade = null, if_all_paid = false, team_name = 'AAABBB', url = null, hackthon_id = 6, teamlead_memberid = 77, hackathon_id = null, hackthon_ids = null WHERE id = 25;
UPDATE openhack.team SET grade = null, if_all_paid = false, team_name = 'BBBCCC', url = null, hackthon_id = 6, teamlead_memberid = 79, hackathon_id = null, hackthon_ids = null WHERE id = 26;
UPDATE openhack.team SET grade = null, if_all_paid = true, team_name = 'DDDSSS', url = null, hackthon_id = 6, teamlead_memberid = 81, hackathon_id = null, hackthon_ids = null WHERE id = 27;
UPDATE openhack.team SET grade = null, if_all_paid = true, team_name = 'tea', url = null, hackthon_id = 6, teamlead_memberid = 83, hackathon_id = null, hackthon_ids = null WHERE id = 28;
UPDATE openhack.team SET grade = null, if_all_paid = false, team_name = 'safd', url = null, hackthon_id = 6, teamlead_memberid = 85, hackathon_id = null, hackthon_ids = null WHERE id = 29;
UPDATE openhack.team SET grade = null, if_all_paid = false, team_name = 'adfs', url = null, hackthon_id = 6, teamlead_memberid = 87, hackathon_id = null, hackthon_ids = null WHERE id = 30;
UPDATE openhack.team SET grade = null, if_all_paid = true, team_name = 'mmmm', url = 'null', hackthon_id = 5, teamlead_memberid = 89, hackathon_id = null, hackthon_ids = null WHERE id = 31;
UPDATE openhack.team SET grade = null, if_all_paid = false, team_name = 'GGG', url = null, hackthon_id = 5, teamlead_memberid = 91, hackathon_id = null, hackthon_ids = null WHERE id = 32;
UPDATE openhack.team SET grade = null, if_all_paid = false, team_name = 'VVV', url = null, hackthon_id = 4, teamlead_memberid = 93, hackathon_id = null, hackthon_ids = null WHERE id = 33;
UPDATE openhack.team SET grade = null, if_all_paid = false, team_name = 'MMM', url = null, hackthon_id = 4, teamlead_memberid = 94, hackathon_id = null, hackthon_ids = null WHERE id = 34;
UPDATE openhack.team SET grade = null, if_all_paid = false, team_name = 'HappyHacker', url = null, hackthon_id = 7, teamlead_memberid = 95, hackathon_id = null, hackthon_ids = null WHERE id = 35;
UPDATE openhack.user SET role = 'User', about_me = null, city = null, state = null, street = null, zip = null, business_title = null, email = 'vera@gmail.com', password = '$2a$10$FOil/RKW3rNzXAO1cONbpuG6cfNt4QwweYoK0.1jQe7roK6.1l/8y', is_verified = null, name = null, portrait = null, username = 'vera', org_id = null WHERE id = 1;
UPDATE openhack.user SET role = 'User', about_me = null, city = null, state = null, street = null, zip = null, business_title = null, email = 'hanhan@gmail.com', password = '$2a$10$gOM7tL7qlkzLvUgSQou1qeKynyjMXflXRDsYGwGKYLlWL.yPYO0T6', is_verified = false, name = null, portrait = null, username = 'hanhan', org_id = null WHERE id = 2;
UPDATE openhack.user SET role = 'User', about_me = null, city = null, state = null, street = null, zip = null, business_title = null, email = 'joe@gmail.com', password = '$2a$10$gRsS00e9ox5DpQGyXSVCg.JFL9Wp7CAjEIkw08IDNqH4ebm1him9e', is_verified = true, name = null, portrait = null, username = 'joe', org_id = null WHERE id = 3;
UPDATE openhack.user SET role = 'admin', about_me = null, city = null, state = null, street = null, zip = null, business_title = null, email = 'bobo@sjsu.edu', password = '$2a$10$/qq5FmITXDElBKLV5hVzc.vTQDZHA.duj1vHVHzcs1eHZv8QaVWFe', is_verified = false, name = null, portrait = null, username = 'bobo', org_id = null WHERE id = 4;
UPDATE openhack.user SET role = 'admin', about_me = null, city = null, state = null, street = null, zip = null, business_title = null, email = 'david@sjsu.edu', password = '$2a$10$g4gwbcETxkItVYzTFf8e2uTnRRL.g3n81xyP3v70tqWHJ5Bmf3eAW', is_verified = true, name = null, portrait = null, username = 'david', org_id = null WHERE id = 5;
UPDATE openhack.user SET role = 'hacker', about_me = null, city = null, state = null, street = null, zip = null, business_title = null, email = 'jam@gmail.com', password = '$2a$10$9nnHoNNO4CVblPc8V7upV.A98g9KxVOV/wgqc17B0xlejBR8gaNDa', is_verified = false, name = null, portrait = null, username = 'jam', org_id = 4 WHERE id = 6;
UPDATE openhack.user SET role = 'admin', about_me = 'SE', city = 'SJ', state = 'CA', street = '123', zip = '95050', business_title = 'Manager', email = 'xiying.wang@sjsu.edu', password = '$2a$10$r8ScWY/B0VbOciupQwOqJe2SWqjj1.fo7E2e8O20RVFJZNAenR7ui', is_verified = true, name = 'Anna', portrait = null, username = 'Wang', org_id = null WHERE id = 7;
UPDATE openhack.user SET role = 'admin', about_me = null, city = null, state = null, street = null, zip = null, business_title = null, email = 'alice@sjsu.edu', password = '$2a$10$Dby3ORP5EWIT7qUdlbmYNO1r7vqkAkjeyfezOguR7odA8BuO8zmrG', is_verified = true, name = null, portrait = null, username = 'Alice', org_id = null WHERE id = 26;
UPDATE openhack.user SET role = 'hacker', about_me = null, city = null, state = null, street = null, zip = null, business_title = null, email = 'wang@test.com', password = '$2a$10$vi.7/YFwzA5VJtf2PIoVje9DXM9SqtzJ/k/NLu5NJArbZ.Kw34/KC', is_verified = true, name = null, portrait = null, username = 'test', org_id = 4 WHERE id = 9;
UPDATE openhack.user SET role = 'hacker', about_me = null, city = null, state = null, street = null, zip = null, business_title = null, email = 'tester@gmail.com', password = '$2a$10$T4hEQUkVJMppH/DBtHvepO8qsB4bwb.5Za3NnT1kl6AELghTdtqNy', is_verified = true, name = null, portrait = null, username = 'abc', org_id = null WHERE id = 10;
UPDATE openhack.user SET role = 'admin', about_me = null, city = null, state = null, street = null, zip = null, business_title = null, email = 'admin@sjsu.edu', password = '$2a$10$2F00iEuIRHUyYAV91gLMJef.gSOIUwyLA4JhVuXl98lScjCtq4Llq', is_verified = true, name = 'abc', portrait = null, username = 'admin', org_id = null WHERE id = 11;
UPDATE openhack.user SET role = 'hacker', about_me = null, city = null, state = null, street = null, zip = null, business_title = null, email = 'alice@gmail.com', password = '$2a$10$b17YCEd4pZwQAaHNVJp06eZfeTeZOz05eomU7Cyk5WR9c6L1k0hGu', is_verified = false, name = null, portrait = null, username = 'alice123', org_id = null WHERE id = 12;
UPDATE openhack.user SET role = 'hacker', about_me = null, city = null, state = null, street = null, zip = null, business_title = null, email = 'john@gmail.com', password = '$2a$10$5RgnDeGCED2Ez8kYfg/OyO9qx9F1vX0PhTW8dammkW/6lEQylS29q', is_verified = false, name = null, portrait = null, username = 'john456', org_id = null WHERE id = 13;
UPDATE openhack.user SET role = 'hacker', about_me = null, city = null, state = null, street = null, zip = null, business_title = null, email = 'jamie@gmail.com', password = '$2a$10$UPYNIFar7iNOmuutFUdHfuVSkDiOHHlXMDpAH0VvBipchGlcIyB8S', is_verified = false, name = null, portrait = null, username = 'jamie456', org_id = null WHERE id = 14;
UPDATE openhack.user SET role = 'hacker', about_me = null, city = null, state = null, street = null, zip = null, business_title = null, email = 'yang.chen.sv@gmail.com', password = '$2a$10$paHn0NFPG4fczT3/dS3E6.WCPkxWqPgCx3fpUuP5Xz5SGh6VtXHAi', is_verified = false, name = null, portrait = null, username = 'cy19890513', org_id = null WHERE id = 15;
UPDATE openhack.user SET role = 'hacker', about_me = null, city = null, state = null, street = null, zip = null, business_title = null, email = 'verawang0112@gmail.com', password = '$2a$10$Q6uqrzMwSyyv5dfRNd0bZ.yO31IE5zA13ryR0abNo2BB.maYN1kWS', is_verified = true, name = null, portrait = null, username = 'vera123', org_id = 9 WHERE id = 16;
UPDATE openhack.user SET role = 'hacker', about_me = 'good engineer', city = 'CUPERTINO', state = 'California', street = '10113 parkwood drive apt8', zip = '95014', business_title = 'engineer', email = 'han@gmail.com', password = '$2a$10$4EQUgpScBmE.sZoLAZbFD.E8r1c/xewBCPFbo8N7qwEJm6stacmCu', is_verified = true, name = 'han', portrait = null, username = 'han''han', org_id = 7 WHERE id = 17;
UPDATE openhack.user SET role = 'hacker', about_me = null, city = null, state = null, street = null, zip = null, business_title = null, email = 'stark@test.com', password = '$2a$10$cKqvRwEgSGDz6zWRforg7eNfvQsMexEAIAEPkMYwiIvFuyjN9rila', is_verified = false, name = null, portrait = null, username = 'stark123', org_id = null WHERE id = 18;
UPDATE openhack.user SET role = 'hacker', about_me = null, city = null, state = null, street = null, zip = null, business_title = null, email = 'janney@gmail.com', password = '$2a$10$VcdKwlo19meVXxqPUvBg/uCwt7Zk.sEnUk5XlzQNc65MQSdesrm4m', is_verified = true, name = null, portrait = null, username = 'janney', org_id = null WHERE id = 19;
UPDATE openhack.user SET role = 'hacker', about_me = null, city = null, state = null, street = null, zip = null, business_title = null, email = 'liruii280@gmail.com', password = '$2a$10$.8ofqj5/aZncGnWiB/CWPumMwLoznZykzDDBPyVrS3h27jwVO4R0i', is_verified = false, name = null, portrait = null, username = 'hacker', org_id = null WHERE id = 20;
UPDATE openhack.user SET role = 'hacker', about_me = null, city = 'san jose', state = 'CA', street = null, zip = null, business_title = null, email = 'monica@test.com', password = '$2a$10$VJryiaGu7KRAz6I/mqxY8.V/ZfdG3s4umHu6kSOVXr.R.eHIl8n72', is_verified = true, name = 'Monica', portrait = null, username = 'monica', org_id = null WHERE id = 21;
UPDATE openhack.user SET role = 'admin', about_me = 'none', city = 'CUPERTINO', state = 'CA', street = 'book', zip = '95014', business_title = 'None', email = 'han@sjsu.edu', password = '$2a$10$DQB8E.oBd5ZAS.u3FCofFeRAzyIpNaa96YzmbNJ1H961.cYg8yrLG', is_verified = true, name = 'user', portrait = null, username = 'test1', org_id = null WHERE id = 22;
UPDATE openhack.user SET role = 'admin', about_me = null, city = null, state = null, street = null, zip = null, business_title = null, email = 'test@sjsu.edu', password = '$2a$10$2F00iEuIRHUyYAV91gLMJef.gSOIUwyLA4JhVuXl98lScjCtq4Llq', is_verified = null, name = null, portrait = null, username = 'adminuser', org_id = null WHERE id = 23;
UPDATE openhack.user SET role = 'admin', about_me = null, city = null, state = null, street = null, zip = null, business_title = null, email = 'newadmin@sjsu.edu', password = '$2a$10$2F00iEuIRHUyYAV91gLMJef.gSOIUwyLA4JhVuXl98lScjCtq4Llq', is_verified = null, name = null, portrait = null, username = 'newadmin', org_id = null WHERE id = 24;
UPDATE openhack.user SET role = 'hacker', about_me = null, city = null, state = null, street = null, zip = null, business_title = null, email = 'bob@gmail.com', password = '$2a$10$nh/ztPwwjPlpctM8pV5geukDT2SGCabOsdfvFzyyTYBZoylH74X0S', is_verified = true, name = null, portrait = null, username = 'Bob', org_id = 10 WHERE id = 25;
UPDATE openhack.user SET role = 'hacker', about_me = null, city = null, state = null, street = null, zip = null, business_title = null, email = 'carl@gmail.com', password = '$2a$10$MQQFfM4pQXrv7DdQiP4FG.yBYiRflXxtQytYJVAPIX5CeibSPyBAK', is_verified = true, name = null, portrait = null, username = 'Carl', org_id = null WHERE id = 27;
